ARG DEBIAN_VERSION=stable
FROM debian:${DEBIAN_VERSION}-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    wireguard \
    iptables \
    iproute2 \
  && rm -rf /var/lib/apt/lists/*

COPY init.sh /

USER root

EXPOSE 51820/udp

ENV CONFIGURATION_DIR=/config
ENTRYPOINT [ "/init.sh" ]
