ARG DEBIAN_VERSION=bookworm
ARG KEY_RING_DIR=/usr/share/keyrings
ARG APT_SOURCES_DIR=/etc/apt/sources.list.d
ARG INSTALL_DIR=/opt/tplink

FROM debian:${DEBIAN_VERSION}-slim AS build
ARG DEBIAN_VERSION
ARG KEY_RING_DIR
ARG APT_SOURCES_DIR
ARG INSTALL_DIR

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
  && apt-get install -y \
    tar \
    curl \
    gpg

ARG MONGO_DB_VERSION=8.0
ARG MONGO_DB_REPO_KEY_PATH=${KEY_RING_DIR}/mongodb-server-${MONGO_DB_VERSION}.gpg
RUN curl -fsSL https://pgp.mongodb.com/server-${MONGO_DB_VERSION}.asc \
  | gpg -o ${MONGO_DB_REPO_KEY_PATH} --dearmor
RUN echo "deb [signed-by=${MONGO_DB_REPO_KEY_PATH}] http://repo.mongodb.org/apt/debian ${DEBIAN_VERSION}/mongodb-org/${MONGO_DB_VERSION} main" \
  | tee ${APT_SOURCES_DIR}/mongodb-org-${MONGO_DB_VERSION}.list

ARG ADOPTIUM_REPO_KEY_PATH=${KEY_RING_DIR}/adoptium.asc
RUN curl -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public \
  | tee ${ADOPTIUM_REPO_KEY_PATH}
RUN echo "deb [signed-by=${ADOPTIUM_REPO_KEY_PATH}] https://packages.adoptium.net/artifactory/deb ${DEBIAN_VERSION} main" \
  | tee ${APT_SOURCES_DIR}/adoptium.list

WORKDIR ${INSTALL_DIR}
ARG OMADA_TAR_URL=https://static.tp-link.com/upload/software/2026/202601/20260121/Omada_Network_Application_v6.1.0.19_linux_x64_20260117100056.tar.gz
RUN curl -fsSL ${OMADA_TAR_URL} | tar -xz -C . --strip-components=1
RUN sed -i "/\${link_name} start/d" ./install.sh

FROM debian:${DEBIAN_VERSION}-slim
ARG KEY_RING_DIR
ARG APT_SOURCES_DIR
ARG INSTALL_DIR

# Needed for adoptium repository.
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Create the user, but do not switch to it. The controller start script expects root.
ENV OMADA_USER=omada
RUN useradd --system -U --shell /usr/sbin/nologin ${OMADA_USER}
USER root

COPY --from=build ${KEY_RING_DIR} ${KEY_RING_DIR}
COPY --from=build ${APT_SOURCES_DIR} ${APT_SOURCES_DIR}
COPY --from=build --chown=${OMADA_USER}:${OMADA_USER} ${INSTALL_DIR} ${INSTALL_DIR}

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    procps \
    curl \
    mongodb-org \
    temurin-17-jre \
    jsvc \
    libcap2-bin \
  && rm -rf /var/lib/apt/lists/*

# Link mongod to the correct location for the controller startup script.
RUN ln -sf "$(which mongod)" ${INSTALL_DIR}/bin/mongod

# https://www.tp-link.com/us/support/faq/865/
#   The Omada Controller does not seem to actually listen on port 27002.
#   The MongoDB port should not be open to the network (the process only listens on localhost anyway).
# Highly recommend using reverse proxy for TLS. Built-in web server uses weak encryption
# and does not support user-configured HTTPS port nor user-configured TLS certificates.
ENV HTTP_PORT=8088
# Web interface
EXPOSE ${HTTP_PORT}/tcp
EXPOSE 8043/tcp
# Omada controller discovery
EXPOSE 27001/udp
# Omada EAP discovery
EXPOSE 29810/udp
# Omada EAP management
EXPOSE 29811/tcp
# Omada EAP adoption
EXPOSE 29812/tcp
# Omada EAP firmware upgrade
EXPOSE 29813/tcp
# Omada EAP device management
EXPOSE 29814/tcp
EXPOSE 29815/tcp
EXPOSE 29816/tcp
EXPOSE 29816/tcp
EXPOSE 29817/tcp

WORKDIR ${INSTALL_DIR}
CMD [ "/bin/bash", "-c", "set -e; ./bin/control.sh start; sleep infinity;" ]
