---
- ansible.builtin.include_tasks: install_certbot.yml

- when: certbot_deploy_hook is not none
  block:
    - name: Create deploy hook dir
      become: true
      ansible.builtin.file:
        path: "{{ certbot_deploy_hook_dir }}"
        state: directory
        owner: root
        group: root
        mode: '755'

    - name: Add deploy hook
      become: true
      # The first line of the file is reserved for a shebang so blockinfile cannot work
      ansible.builtin.template:
        src: deploy_hook.sh.j2
        dest: "{{ certbot_deploy_hook_dir }}/ansible_hook.sh"
        owner: root
        group: root
        mode: '700'

- name: Find existing certificates
  become: true
  ansible.builtin.command: "{{ certbot_path | quote }} certificates"
  register: certbot_existing_certs
  changed_when: false

- ansible.builtin.include_tasks: dns.yml
  when: certbot_use_dns
- ansible.builtin.include_tasks: standalone.yml
  when: not certbot_use_dns

# certbot hides this directory by default, presumably to avoid leaking which domains are hosted on the server
# which is irrelevant if the server is not shared
- name: Allow unprivileged users to read /etc/letsencrypt/live (but not the certificates)
  become: true
  ansible.builtin.file:
    path: /etc/letsencrypt/live
    mode: '755'
