---
- name: OS-specific configuration
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}.yml"
    apply:
      become: true

- name: Create directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}"
    state: directory
    mode: '755'

- name: Configure Docker daemon
  become: true
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '644'
  register: docker_daemon_configuration

- name: Restart Docker daemon
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
  when: docker_daemon_configuration is changed

- when: docker_daemon_userns_remap is defined
  block:
    - name: Read remapped user ID file
      ansible.builtin.slurp:
        src: /etc/subuid
      register: docker_daemon_userns_remap_file

    - name: Set remapped user ID fact
      become: true
      ansible.builtin.set_fact:
        docker_remap_user: "{{
          ((docker_daemon_userns_remap_file['content'] | b64decode).splitlines()
            | select('search', 'dockremap')
            | first
            | split(':'))[1]}}"

- name: Schedule docker system prune
  become: true
  ansible.builtin.cron:
    name: Prune unused docker resources
    state: present
    special_time: daily
    job: docker system prune -f
