ARG CADDY_VERSION=2

# Build Caddy with the Cloudflare DNS plugin
FROM caddy:${CADDY_VERSION}-builder AS builder
RUN xcaddy build --with github.com/caddy-dns/cloudflare

# Create the final image
FROM caddy:${CADDY_VERSION}
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

USER root
