---
- name: (RedHat) Install Netbird dependencies
  ansible.builtin.dnf:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: (RedHat) Add package repositories
  ansible.builtin.yum_repository:
    name: netbird
    description: Official Netbird packages
    baseurl: "https://pkgs.netbird.io/yum/"
    gpgcheck: true
    gpgkey: "https://pkgs.netbird.io/yum/repodata/repomd.xml.key"
    repo_gpgcheck: true
    enabled: true

- name: (RedHat) Install Netbird
  when: not ansible_check_mode
  ansible.builtin.dnf:
    name:
      - netbird
    state: present
