---
name: Build Caddy image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_caddy_cloudflare.yml
      - ansible/dockerfiles/caddy_cloudflare/**
  pull_request:
    paths:
      - .github/workflows/build_caddy_cloudflare.yml
      - ansible/dockerfiles/caddy_cloudflare/**

jobs:
  build:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/push_docker_image.yml
    with:
      image_name: ghcr.io/niklasea/caddy_cloudflare
      context: ansible/dockerfiles/caddy_cloudflare
      file: ansible/dockerfiles/caddy_cloudflare/dockerfile
